apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: db-secret
  namespace: dbservice
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA+PFwDePOVBPVqoYgDsVCiWxTqaxJ+qS2AgD6OG6THPur6EVWnXH2RNAILqlJ+ZJVNt9mTWRvzp7TRbgHweXv/PMRSZflWePMhAUfkiDnXVL4ayMcc7+MyjoOSHPdCUlXTMdszYQe4WyULQ4UJwNI5p391FywuGr5oVarIwOV6CDHeW4xI2TYPDRFAfuqitRBqMEkG7gAyw/iid/Z4DqqblLds02lnv2lKU07oc3Bn+KyoX7Hj4xwwXQW9gy98Ogv975sGr0Nj9ZqJasTvGE/Z+FpR6ecd+wGMG4zLB0rlNg7C8CN3dO/xnbTUwTNB/s9IFLVm9GYsu3efdS155nJrdpGMWBeLIVVaIgaIqss+yURLbTd+C5yvmW0nqUwUSuU2a4NpPZkdygk6Pq0deduwOgsgi+xVdW2gXfl2newcInI6cWRvwxO+ftSFwrMyrbe85FhLbhWPA1HA7+U34/X85b87xb2myFMClSDh0jN6ROqEy5C6iJQc+EQP74nwKxxNnUD37I173IkcENBjkPbbu/9Oku+4Bd/N2Ex+7/Cg+2LnQKs0IcVHlaD7hTwFV8fys/etgwVFCl6l//0hv/6NNk9JcA+3CrFIMlnwQBRNuswemcer5g3gewvNqDKuKlR0o8enSaL8dg//NUxbyh5aN0loDGVCg9PI3aOHckOWcnMsITaXrRFmXijG0aIxRXEf5R4rdd+5ZdKpyCBERjt2D4rvEP8drRM=
    POSTGRES_POSTGRES_PASSWORD: AgBuxuJtipf238ZzAGBoCGxekkdiBaeMCTX3XvhVajtQ18fh0SwGPMpWZKEpaX89Sq5i18jtBoytZrb9pV3ry9NistLwPbKTxgNnHC5pY+FSksD29xdMjdcN0lPCX2HTKVvTGEJbdwLAw6/XcnzIWRkrZtFTdI+5hiTeMnCmWtYFGl5jtkdB5dnnX/7ZscvzijTlXbkG5uh3T02EUmeZGeJU2ZVpSamksZKdlp+HHVzY0OOMC7jg44qaGoFlneKm6EOfet54EB0Tu+aZ3DOxtnwAoYzYz9Oxw4ZcqWytoWYDh7Adnh9SPnBZdrVN0fE/l6e9d6HAp2g0EkK+PjZbsr/BMOXhargk/ELAQx3boZ2R3R534R9JGen6H3l/HMMA72rkPUa2ZkY+A33tyT9lA0TmPqqAELea1AFAnyEmsOMyrBqr9yOHegoebYuFCnU3KSXKLAuZ2bmvVW1DwRliv90TzHdnbqLMs5I6L6j/aeznaidBPli42HidqJR6Puq9Fj2q/SvWxT8jrY2pR7LU5CgGMqCxn+f8zHHGAgBqjMbxyJTdmIC22ujid2Oz+XTNGa7cWULAlbCC/q1QJAdyc9iDgMr3l82bFmf6/tsxXEVc3TcvAintOWKMBKoLlMY4qJrXz66ADBYHP9p065Qv1rPNuIaMg6oy1RTegRzCI/vQC9W9cxLaNDZvhcPhc0cKdobnixAZWg3EkgVgMRMm+UmdFmiQnpdS/Lg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: db-secret
      namespace: dbservice
    type: Opaque

