---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  
  - ../../components/redis
  
namespace: "redisservice"
namePrefix: "redisservice-"
images:
  - name: "traefik/whoami"
    newTag: "v1.9"
  
  - name: "docker.io/bitnami/redis"
    newTag: "6.2.12"
configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
  
